site_name: AulaFischX
theme:
  name: material

nav:
  - Inicio: index.md
  - Registro de Estudiantes: registro_estudiantes.md
  - Creación de Cursos: creacion_cursos.md
  - Asignación de Roles: asignacion_roles.md

extra_javascript:
  - https://unpkg.com/driver.js/dist/driver.min.js
  - extra.js

extra_css:
  - https://unpkg.com/driver.js/dist/driver.min.css
