site_name: AulaFischX
theme:
  name: material

nav:
  - Inicio: index.md
  - Registro de Estudiantes: registro_estudiantes.md
  - Creación de Cursos: creacion_cursos.md
  - Asignación de Roles: asignacion_roles.md

extra_javascript:
  - https://cdn.jsdelivr.net/npm/driver.js@1.0.1/dist/driver.min.js
  - extra.js

extra_css:
  - https://cdn.jsdelivr.net/npm/driver.js@1.0.1/dist/driver.min.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com
  csp:
    default-src: ["'self'", "https://cdn.jsdelivr.net"]
    script-src: ["'self'", "https://cdn.jsdelivr.net"]
    style-src: ["'self'", "https://cdn.jsdelivr.net"]
