site_name: AulaFischX

theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png
  features:
    - navigation.tabs
    - navigation.top
    - header.autohide
    - navigation.sections        # Activa secciones en la navegación izquierda
    - navigation.indexes         # Permite indexar múltiples páginas


extra_css:
  - styles/extra.css
  - https://cdn.jsdelivr.net/npm/shepherd.js/dist/css/shepherd.css
  - https://fonts.googleapis.com/icon?family=Material+Icons

extra_javascript:
  - https://cdn.jsdelivr.net/npm/shepherd.js/dist/js/shepherd.min.js
  - styles/extra.js
  - https://fonts.googleapis.com/icon?family=Material+Icons

nav:
  - Inicio: index.md
  - Documentación para profesores: teacher.md
  - Documentación para estudiantes: student.md
  - Documentación para admin:
      - Introducción: admin.md
      - Configuración inicial: admin/configuracion.md
      - Gestión de usuarios: admin/usuarios.md
      - Seguridad y respaldo: admin/seguridad.md
      - Personalización: admin/personalizacion.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - attr_list  
