site_name: AulaFischX
theme:
  name: material

nav:
  - Inicio: index.md
  - Registro de Estudiantes: registro_estudiantes.md
  - Creación de Cursos: creacion_cursos.md
  - Asignación de Roles: asignacion_roles.md

extra_javascript:
  - https://unpkg.com/driver.js@1.0.1/build/driver.min.js
  - extra.js

extra_css:
  - https://unpkg.com/driver.js@1.0.1/build/driver.min.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com
  # 👇 Esto permite recursos externos de manera segura
  csp:
    default-src: ["'self'", "https://unpkg.com"]
    script-src: ["'self'", "https://unpkg.com"]
    style-src: ["'self'", "https://unpkg.com"]
