site_name: AulaFischX
theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.tabs.link
    - content.code.copy
    - header.autohide

nav:
  - Home: index.md
  - Registro de Estudiantes: registro_estudiantes.md
  - Creación de Cursos: creacion_cursos.md
  - Asignación de Roles: asignacion_roles.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com
