site_name: AulaFischX
theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png
  features:
    - navigation.tabs
    - navigation.top
    - header.autohide

extra_css:
  - styles/extra.css
  - https://cdn.jsdelivr.net/npm/shepherd.js/dist/css/shepherd.css  # 🔥 Shepherd.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/shepherd.js/dist/js/shepherd.min.js # 🔥 Shepherd.js
  - styles/extra.js

nav:
  - Inicio: index.md
  - Documentación para profesores: teacher.md
  - Documentación para estudiantes: student.md
  - Documentación para admin: admin.md

